lms-rangga-master/lms/apps/login/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('auth/', views.login, name="login"),
    path('logout/', views.logout, name="logout")
]

lms-rangga-master/lms/lms/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', include(('apps.admin.urls','admin'), namespace="admin")),
    path('guru/', include(('apps.guru.urls','guru'), namespace="guru")),
    path('siswa/', include(('apps.siswa.urls','siswa'), namespace="siswa")),
    path('login/', include(('apps.login.urls','login'), namespace="login")),
    path('dashboard/', include(('apps.dashboard.urls','dashboard'), namespace="dashboard"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lms-rangga-master/lms/templates/common/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2021</span>
        </div>
    </div>
</footer>

lms-rangga-master/lms/templates/common/header.html
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>
    {% include 'common/links.html' %}
    <!-- Custom fonts for this template-->
    

</head>

lms-rangga-master/lms/templates/common/links.html
{% load static %}
<link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

lms-rangga-master/lms/templates/common/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
           
            <div class="input-group-append">
                
                <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modalIndexNilai">
                    Indeks Nilai
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <button class="nav-link" type="button" data-toggle="modal" data-target="#modalIndexNilai">
                Indeks Nilai
            </button>
            
        </li>

        

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ profile_name }}</span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'login:logout' %}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<div class="modal fade" id="modalIndexNilai" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Approve</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <table>
                <thead>
                    <tr>
                        <th>Indeks Nilai</th>
                        <th>Label</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>>=5</td>
                        <td>Sangat Baik</td>
                    </tr>
                    <tr>
                        <td>>=4</td>
                        <td>Baik</td>
                    </tr>
                    <tr>
                        <td>>=3</td>
                        <td>Cukup</td>
                    </tr>
                    <tr>
                        <td>>=2</td>
                        <td>Kurang</td>
                    </tr>
                    <tr>
                        <td>>=1</td>
                        <td>Sangat Kurang</td>
                    </tr>
                    <tr>
                        <td>>=0</td>
                        <td>Tidak Lulus</td>
                    </tr>
                </tbody>
                

            </table>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

lms-rangga-master/lms/templates/common/scripts.html
{% load static %}
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static "js/sb-admin-2.min.js" %}"></script>

<!-- Page level plugins -->
<script src="{% static "vendor/chart.js/Chart.min.js" %}"></script>

lms-rangga-master/lms/templates/common/sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">  <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:index' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Dashboard</span></a>
    </li>
    <!-- Nav Item - Dashboard -->
    {% if request.session.role == "admin" %}
        {% include 'common/role_sidebar/admin.html' %}
    {% endif %}
    {% if request.session.role == "guru" %}
        {% include 'common/role_sidebar/guru.html' %}
    {% endif %}
    {% if request.session.role == "siswa" %}
        {% include 'common/role_sidebar/siswa.html' %}
    {% endif %}
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>