lms-rangga-master/lms/apps/login/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('auth/', views.login, name="login"),
    path('logout/', views.logout, name="logout")
]

lms-rangga-master/lms/lms/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', include(('apps.admin.urls','admin'), namespace="admin")),
    path('guru/', include(('apps.guru.urls','guru'), namespace="guru")),
    path('siswa/', include(('apps.siswa.urls','siswa'), namespace="siswa")),
    path('login/', include(('apps.login.urls','login'), namespace="login")),
    path('dashboard/', include(('apps.dashboard.urls','dashboard'), namespace="dashboard"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lms-rangga-master/lms/apps/login/models.py
from models.mainModel import mainModel, paramsGenerator
column = ["id_guru", "nama","jenis_kelamin","tanggal_lahir"]
class Model(mainModel):
    def getUser(self, data={}):
        try:
            params, values = paramsGenerator(data)
            self.cursor.execute("SELECT id_user, username, password, role, user_role_id FROM user where "+params, values)
            res = self.cursor.fetchone()
            self.result = {
                "data":res,
                "action":"select"
            }
            return self
        except Exception as e:
            print(e)

    

lms-rangga-master/lms/apps/login/views.py
from django.shortcuts import render, redirect
from .models import Model
# Create your views here.
model = Model()
def index(request):
    return render(request, 'login/index.html')

def login(request):
    print(request.POST.get("username"))
    data = model.getUser({
        "username":request.POST.get("username"),
        "password":request.POST.get("password")
    }).getResult()
    print("DATANYA:")
    print(data)
    if data != None:
        if data['role'] == "admin":
            request.session['user_role_id'] = "admin"
        else:
            request.session['user_role_id'] = data['user_role_id']
        request.session['role'] = data['role']
        return redirect('/dashboard')
    return redirect("/login")

def logout(request):
    del request.session['user_role_id']
    del request.session['role']
    return redirect("/login")

lms-rangga-master/lms/templates/login/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" action="{% url 'login:login' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                placeholder="Username..." name="username">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" name="password" placeholder="Password">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>